#!/bin/zsh
# -*- sh -*-

export PATH="$HOME/bin/:$PATH"

if [ "$(hostname)" = "reger" ]; then
    export PATH="$PATH:/home/jonny/src/git-branch-tools"
    export PATH="$PATH:/home/jonny/src/rpi-scripts"
fi
