#!/bin/zsh
# -*- sh -*-

autoload -Uz compinit

zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*:(all-|)files' ignored-patterns '(|*/)*.(pyc|o|lo|egg-info|class)'

zstyle :compinstall filename '$ZDOTDIR/zshrc.d/010_completion'

