#!/bin/zsh
# -*- sh -*-

autoload -Uz vcs_info
setopt PROMPT_SUBST

DEBIAN_CHROOT=""
JHBUILD=""

# chroot
if [ -r "/etc/debian_chroot" ]; then
    local debian_chroot=$(cat /etc/debian_chroot)
    DEBIAN_CHROOT="${debian_chroot:+/%S$debian_chroot%s}"
fi

# jhbuild
if [ "$UNDER_JHBUILD" = "true" ]; then
    JHBUILD="/%{$fg_bold[green]%}jhbuild%{$reset_color%}"
fi

# show a normal prompt for normal sessions, otherwise include username
# and make it red and bold in all other cases
if [ $USER = jonny ] || [ $USER = jlamb ]; then
    PROMPT="%B%M%b${DEBIAN_CHROOT}${JHBUILD}:%~%# "
else
    PROMPT="%{$fg_bold[red]%}%n@%B%M%b${DEBIAN_CHROOT}${JHBUILD}:%~%# "
fi

# I can't remember what any of these do
zstyle ':vcs_info:*' formats '%u%F{0}%b%f%c'
zstyle ':vcs_info:*' actionformats '%u%F{1}%b/%a%f%c'

zstyle ':vcs_info:bzr:*' use-simple true

zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' stagedstr '*'
zstyle ':vcs_info:*' unstagedstr '*'

# toggle so vcs_info can be switched off
ENABLE_VCS_INFO="yes"
togglegit () {
    if [ "$ENABLE_VCS_INFO" = "yes" ]; then
        ENABLE_VCS_INFO="no"
    else
        ENABLE_VCS_INFO="yes"
    fi
}

# fast and super ugly git command(s)
_git_branch () {
    branchname=`cat $(git rev-parse --show-toplevel)/.git/HEAD`
    echo ${branchname//ref: refs\/heads\//}
}

precmd () {
    if [ -f /etc/debian_chroot ]; then
        vcs_info_msg_0_=""
    elif [ "$(git config --get core.usewatchman)" = "true" ] || [ $ENABLE_VCS_INFO = "no" ]; then
        vcs_info_msg_0_="%{$fg[grey]%}`_git_branch`%{$reset_color%}"
    elif [ $ENABLE_VCS_INFO = "yes" ]; then
        vcs_info
    fi
    RPROMPT=' %B${vcs_info_msg_0_}%b %(?..%?)'
}
