#!/bin/zsh
# -*- sh -*-

alias irc="mosh berg -- screen -ax"
alias dirc="ssh berg screen -d"

# typos
alias EXIT="exit"
alias sl="ls"
alias Grep="grep"
alias cd..="cd .."

# apt
alias sagi="sudo apt-get install"
alias sagr="sudo apt-get remove"
alias sagu="sudo apt-get update"
alias acs="apt-cache search"
alias acsh="apt-cache show"
alias afs="apt-file search -x"
alias acp="apt-cache policy"

# editors
alias e=$EDITOR
alias se="sudo emacs -nw"
alias ec="emacsclient -n"

# git
alias gd="git diff"
alias g="gd"
alias gs="gis"
alias gis="git --no-pager status -sb"
alias gdc="git diff --cached"
alias gc="git commit -v"
alias gca="git commit -va"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gcm="git checkout master"
alias gl="git log"
alias ga="git add"
alias gcf="git commit --fixup"
alias gpom="git pull --ff-only origin master"
alias gpmm="git push annarchy master:master"

# misc
alias s="sudo"
alias ls="ls --color"
alias l="ls"
alias ll="ls -lh"
alias la="ls -lha"
alias diff="diff -Nruad"
alias tf="tail -f"
alias stf="sudo tail -f"
alias MAKE="make"
alias m="colormake V=0"
alias mc="make check"
alias fn="find -name"
alias d="debcommit"
alias msot="most"

# ag
alias ag="ag --path-to-agignore ~/.agignore"
alias agmain="ag --ignore test"
alias agtest="ag --ignore main"

# global aliases
alias -g ...="../.."
alias -g ....="../../.."

# noglobbing
alias curl="noglob curl"
alias wget="noglob wget"
alias epiphany="noglob epiphany"
alias find="noglob find"

# misc rubbish
alias shipit='for i in /usr/local/share/cows/*.cow; do cowsay -f $i "Ship it"; done'
