#!/bin/zsh
# -*- sh -*-

if [ -d $HOME/src/zsh-git-escape-magic ]; then
    fpath=($HOME/src/zsh-git-escape-magic $fpath)
    autoload -Uz git-escape-magic
    git-escape-magic
fi

git () {
    # if git doesn't point to /usr/bin/git, there are going to be big
    # problems so don't bother going ahead
    original="$(sh -c 'which git')"
    if ! [ "$original" = "/usr/bin/git" ]; then
        $original $@
        return
    fi

    if [ "`/usr/bin/git config --local --get user.email`" = "jonny.lamb@collabora.co.uk" ]; then
        /usr/bin/git config --local --unset user.email
    fi

    if ! /usr/bin/git config --local --get user.email 2>&1 > /dev/null && \
       echo $1 | grep -E "^(commit|merge|rebase|am|cherry-pick|revert)$" 2>&1 > /dev/null; then

        tmp=`mktemp`

        if ! dialog --menu "pick an email address" \
               11 50 4 \
               jonnylamb@jonnylamb.com personal \
               jonny@debian.org debian \
               jonnylamb@gnome.org gnome 2> $tmp; then
            return
        fi

        email=`cat $tmp`
        rm $tmp

        /usr/bin/git config --local user.email $email

    fi

    /usr/bin/git $@
}
