#!/bin/zsh
# -*- sh -*-

git () {
    if ! /usr/bin/git config --local --get user.email 2>&1 > /dev/null && \
       echo $1 | grep -E "^(commit|merge|rebase|am|cherry-pick|revert)$" 2>&1 > /dev/null; then

        tmp=`mktemp`

        if ! dialog --menu "pick an email address" \
               11 50 4 \
               jonnylamb@jonnylamb.com personal \
               jonny.lamb@collabora.co.uk collabora \
               jonny@debian.org debian \
               jonnylamb@gnome.org gnome 2> $tmp; then
            return
        fi

        email=`cat $tmp`
        rm $tmp

        /usr/bin/git config --local user.email $email

    fi

    /usr/bin/git $@
}
