#!/bin/zsh
# -*- sh -*-

git () {
    if ! /usr/bin/git config --local --get user.email 2>&1 > /dev/null && \
       echo $1 | grep -E "^(commit|merge|rebase|am|cherry-pick|revert)$" 2>&1 > /dev/null; then

        tmp=`mktemp`

        dialog --menu "pick an email address" \
               11 50 4 \
               jonny@debian.org debian \
               jonny.lamb@collabora.co.uk collabora \
               jonnylamb@jonnylamb.com personal \
               jonnylamb@gnome.org gnome 2> $tmp

        email=`cat $tmp`
        rm $tmp

        /usr/bin/git config --local user.email $email

    fi

    /usr/bin/git $@
}

d() {
    /usr/bin/debcommit $@
}

git-bare() {
    [ -d .git ] || { echo "$0: Use inside a current Git repository"; return 1; }
    [ -z $1 ] && { echo "$0: Specify a git repo name"; return 1; }
    [ -e /tmp/$1.git ] && { echo "$0: /tmp/$1.git already exists"; return 1; }

    git clone --bare . /tmp/$1.git
    git --bare --git-dir=/tmp/$1.git update-server-info
    git --bare --git-dir=/tmp/$1.git gc
    mv /tmp/$1.git/hooks/post-update{.sample,}
    chmod +x /tmp/$1.git/hooks/post-update
    touch /tmp/$1.git/git-daemon-export-ok

    sensible-editor /tmp/$1.git/description

    if [ "$2" = "upload" ]; then
	echo "Will upload to jonnylamb.com now.."

	if grep -i "packag" /tmp/$1.git/description; then
	    scp -r /tmp/$1.git jonnylamb@jonnylamb.com:git/packaging/
	else
	    scp -r /tmp/$1.git jonnylamb@jonnylamb.com:git/
	fi
	rm -rf /tmp/$1.git
    else
	echo "Repository is at /tmp/$1.git"
    fi
}

tun() {
    EDITOR=true dch --no-force-save-on-release -r && git add debian/changelog && git commit -m "Target unstable."
}

texperimental() {
    EDITOR=true dch -D experimental --no-force-save-on-release -r && git add debian/changelog && git commit -m "Target experimental."
}
