#!/bin/zsh
# -*- sh -*-

src () {
    [ -z $1 ] && { echo "E: enter project name"; return 1; }

    [ "$1" = "emp" ] && { 1=empathy; }

    if [ -d ~/src/telepathy-$1 ]; then
        dir=~/src/telepathy-$1
    else
        dir=~/src/$1
    fi

    if [ -d $dir ]; then
        cd $dir
    else
        echo "E: No directory: $dir"
    fi
}
