#!/bin/zsh
# -*- sh -*-

g () {
    project=$(basename `pwd`)
    [ -x src/$project ] || return 1
    GABBLE_DEBUG=all SALUT_DEBUG=all EMPATHY_DEBUG=all HAZE_DEBUG=all \
        GABBLE_PERSIST=1 SALUT_PERSIST=1 HAZE_PERSIST=1  EMPATHY_SRCDIR=. \
        libtool --mode=execute gdb -q --args ./src/$project --g-fatal-warnings
}

b () {
    ref=$1
    if [ -z $1 ]; then
        ref=$(git symbolic-ref HEAD 2> /dev/null) || { echo "E: couldn't detect branch"; return 1; }
        ref=${ref#refs/heads/}
    fi

    repo=$(basename `pwd`)
    echo "http://git.collabora.co.uk/?p=user/jonny/$repo.git;a=shortlog;h=refs/heads/$ref"

    # Don't load a web browser if we're in an SSH session, or don't even
    # have a display.
    [ "$SSH_CLIENT" = "" ] && [ ! "$DISPLAY" = "" ] && gnome-open "http://git.collabora.co.uk/?p=user/jonny/$repo.git;a=shortlog;h=refs/heads/$ref"
}
