#!/bin/zsh
# -*- sh -*-

genpackages() {
    dpkg-scanpackages . /dev/null | tee Packages | gzip -9 > Packages.gz
    dpkg-scansources . /dev/null | tee Sources | gzip -9 > Sources.gz
}

tun() {
    EDITOR=true dch --no-force-save-on-release -r \
        && git add debian/changelog \
        && git commit -m "Target unstable."
}

texperimental() {
    EDITOR=true dch -D experimental --no-force-save-on-release -r \
        && git add debian/changelog \
        && git commit -m "Target experimental."
}
