#!/bin/zsh
# -*- sh -*-

cdt () {
    cdt_dir=/tmp/
    if [ -n "$CDT_PATH" ]; then
	cdt_dir=$CDT_PATH
    fi

    cd $(mktemp -p $cdt_dir -td cdt.XXXXXX);
    echo "Moved to $(pwd)"
}

fcdt () {
    for i in $(find /tmp/ -name $1 2>/dev/null | grep "^/tmp/cdt"); do
        echo $(dirname $i) → $i
    done
}
