#!/bin/zsh
# -*- sh -*-

sdhansak() {
    scp -C $@ jonny@dhansak.collabora.co.uk:public_html/ && echo "\nhttp://people.collabora.co.uk/~jonny/$(basename $1)"
}

sbyte() {
    scp -C $@ jonnylamb@jonnylamb.com:jonnylamb.com/htdocs/uploads/ && echo "\nhttp://jonnylamb.com/uploads/$(basename $1)"
}
