#!/bin/zsh
# -*- sh -*-

case $HOST in
    vega*)
	export http_proxy="http://wwwcache.dur.ac.uk:8080"
	;;
    compsoc*)
	export http_proxy="http://wwwcache.dur.ac.uk:8080"
	# This is just silly. sudo reports are there for a reason.
	alias sudo="/usr/bin/sudo"
	;;
esac

# TODO: clean up thoroughly. :-(
bt() {
    host="corelli"

    if [ "`/sbin/ifconfig eth0 | grep "inet addr" | awk '{print $2}'`" != "addr:192.168.0.101" ]; then
        if [ "`/sbin/ifconfig wlan0 | grep "inet addr" | awk '{print $2}'`" != "addr:192.168.0.102" ]; then
            host="corelli.jonnylamb.com"
        fi
    fi

    ssh -v -t "jonny@$host" "screen -ax"
}